---
- name: Deploy WWT Application
  hosts: all
  gather_facts: false
  become: true
  vars:
    host_port: 8080
    # app runs on 8080 so don't change unless app.py modified and image pushed
    container_port: 8080
    container_name: wwt-demo-app

  tasks:
    - name: Podman install
      ansible.builtin.dnf:
        name: podman
        state: present

    - name: See if container exists
      containers.podman.podman_container_info:
        name: "{{ container_name }}"
      register: container_info

    - name: Create or Update Application Container
      containers.podman.podman_container:
        name: "{{ container_name }}"
        image: quay.io/nsthompson/wwt-demo-app:latest
        state: started
        recreate: "{{ 'true' if container_info['containers'] is iterable | default(false) }}"
        network: bridge
        ports:
          - "{{ host_port }}:{{ container_port }}"
        env:
          HEADER_COLOR: "{{ header_color }}"
          HEADER_TITLE: "{{ header_title }}"
      register: container

    - name: Print container
      ansible.builtin.debug:
        var: container
