---
- name: Restart Demo Application
  hosts: all
  gather_facts: false
  vars:
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    cluster_url: "{{ hostvars[inventory_hostname].cluster_url }}"

  tasks:
    - name: Scale Application Deployment to 0
      kubernetes.core.k8s_scale:
        host: "{{ cluster_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        api_version: v1
        kind: Deployment
        name: "{{ deployment_name }}"
        namespace: "{{ namespace }}"
        replicas: 0
        validate_certs: false

    - name: Scale Application Deployment to 1
      kubernetes.core.k8s_scale:
        host: "{{ cluster_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        api_version: v1
        kind: Deployment
        name: "{{ deployment_name }}"
        namespace: "{{ namespace }}"
        replicas: 1
        validate_certs: false
